spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: microservicecloud-config-exer-dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-exer-test
#请保存为UTF-8格式